
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CARDINALITY CHARACTER COMPOSITION DELIMITER DIGIT ID MODALITYexpression : definition\n       | assignmentdefinition : CARDINALITY entity MODALITY relation CARDINALITY entitydefinition : CARDINALITY entity relation CARDINALITY entityassignment : entity COMPOSITION attributelistentity : IDrelation : IDattributelist : attributelist DELIMITER ID\n   | ID '
    
_lr_action_items = {'DELIMITER':([9,10,17,],[-9,14,-8,]),'$end':([1,3,4,6,9,10,17,18,20,],[-1,0,-6,-2,-9,-5,-8,-4,-3,]),'ID':([0,4,5,7,8,13,14,15,19,],[4,-6,4,9,12,12,17,4,4,]),'COMPOSITION':([2,4,],[7,-6,]),'CARDINALITY':([0,11,12,16,],[5,15,-7,19,]),'MODALITY':([4,8,],[-6,13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'definition':([0,],[1,]),'entity':([0,5,15,19,],[2,8,18,20,]),'expression':([0,],[3,]),'attributelist':([7,],[10,]),'relation':([8,13,],[11,16,]),'assignment':([0,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> definition','expression',1,'p_expression','ERLex.py',83),
  ('expression -> assignment','expression',1,'p_expression','ERLex.py',84),
  ('definition -> CARDINALITY entity MODALITY relation CARDINALITY entity','definition',6,'p_definition_modality','ERLex.py',93),
  ('definition -> CARDINALITY entity relation CARDINALITY entity','definition',5,'p_definition','ERLex.py',101),
  ('assignment -> entity COMPOSITION attributelist','assignment',3,'p_assignment','ERLex.py',108),
  ('entity -> ID','entity',1,'p_entity','ERLex.py',114),
  ('relation -> ID','relation',1,'p_relation','ERLex.py',119),
  ('attributelist -> attributelist DELIMITER ID','attributelist',3,'p_attributelist','ERLex.py',124),
  ('attributelist -> ID','attributelist',1,'p_attributelist','ERLex.py',125),
]
